"""
Nimbus-1 Training Script

Trains a ~124M parameter decoder-only transformer on tokenized text data.
Supports gradient accumulation, mixed precision (bfloat16), and checkpointing.

Usage:
    python train.py                           # default config
    python train.py --config configs/nimbus_1.yaml
    python train.py --resume out/ckpt.pt      # resume from checkpoint

Expected data layout:
    data/train.bin
    data/val.bin
(generated by data/prepare.py)
"""

import os
import time
import math
import yaml
import argparse
import contextlib
from dataclasses import dataclass, asdict

import numpy as np
import torch

from model.transformer import Nimbus, NimbusConfig
from data.dataset import get_dataloader


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

@dataclass
class TrainConfig:
    # Data
    data_dir: str = "data"
    out_dir: str = "out"

    # Model
    n_layer: int = 12
    n_head: int = 12
    n_embd: int = 768
    block_size: int = 1024
    vocab_size: int = 50257
    dropout: float = 0.0
    bias: bool = True

    # Training
    max_iters: int = 19_073          # ~10B tokens at batch of 524k
    batch_size: int = 8              # micro-batch (sequences per GPU step)
    grad_accum_steps: int = 64       # total batch = 8 * 64 * 1024 = 524,288 tokens
    eval_interval: int = 500
    eval_iters: int = 100
    log_interval: int = 10
    save_interval: int = 1000

    # Optimizer
    learning_rate: float = 6e-4
    weight_decay: float = 0.1
    beta1: float = 0.9
    beta2: float = 0.95
    grad_clip: float = 1.0

    # LR schedule (cosine decay with warmup)
    warmup_iters: int = 715          # ~375M tokens
    lr_decay_iters: int = 19_073
    min_lr: float = 6e-5             # = learning_rate / 10

    # System
    device: str = "cuda"
    dtype: str = "bfloat16"
    compile: bool = True
    seed: int = 1337


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--config", type=str, default=None)
    p.add_argument("--resume", type=str, default=None)
    return p.parse_args()


# ---------------------------------------------------------------------------
# LR schedule
# ---------------------------------------------------------------------------

def get_lr(cfg: TrainConfig, it: int) -> float:
    if it < cfg.warmup_iters:
        return cfg.learning_rate * it / cfg.warmup_iters
    if it > cfg.lr_decay_iters:
        return cfg.min_lr
    decay_ratio = (it - cfg.warmup_iters) / (cfg.lr_decay_iters - cfg.warmup_iters)
    coeff = 0.5 * (1.0 + math.cos(math.pi * decay_ratio))
    return cfg.min_lr + coeff * (cfg.learning_rate - cfg.min_lr)


# ---------------------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------------------

@torch.no_grad()
def estimate_loss(model, train_loader, val_loader, cfg: TrainConfig, ctx):
    model.eval()
    results = {}
    for split, loader in [("train", train_loader), ("val", val_loader)]:
        losses = []
        it = iter(loader)
        for _ in range(cfg.eval_iters):
            try:
                x, y = next(it)
            except StopIteration:
                it = iter(loader)
                x, y = next(it)
            x, y = x.to(cfg.device), y.to(cfg.device)
            with ctx:
                _, loss = model(x, y)
            losses.append(loss.item())
        results[split] = float(np.mean(losses))
    model.train()
    return results


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    args = parse_args()
    cfg = TrainConfig()

    if args.config:
        with open(args.config) as f:
            overrides = yaml.safe_load(f)
        for k, v in overrides.items():
            if hasattr(cfg, k):
                setattr(cfg, k, v)

    os.makedirs(cfg.out_dir, exist_ok=True)

    torch.manual_seed(cfg.seed)
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True

    device_type = "cuda" if "cuda" in cfg.device else "cpu"
    ptdtype = {
        "float32": torch.float32,
        "bfloat16": torch.bfloat16,
        "float16": torch.float16,
    }[cfg.dtype]
    ctx = (
        contextlib.nullcontext()
        if device_type == "cpu"
        else torch.amp.autocast(device_type=device_type, dtype=ptdtype)
    )

    # Data
    train_loader = get_dataloader(
        os.path.join(cfg.data_dir, "train.bin"),
        block_size=cfg.block_size,
        batch_size=cfg.batch_size,
        shuffle=True,
    )
    val_loader = get_dataloader(
        os.path.join(cfg.data_dir, "val.bin"),
        block_size=cfg.block_size,
        batch_size=cfg.batch_size,
        shuffle=False,
    )

    # Model
    model_cfg = NimbusConfig(
        vocab_size=cfg.vocab_size,
        n_layer=cfg.n_layer,
        n_head=cfg.n_head,
        n_embd=cfg.n_embd,
        block_size=cfg.block_size,
        dropout=cfg.dropout,
        bias=cfg.bias,
    )

    iter_num = 0
    best_val_loss = float("inf")

    if args.resume:
        print(f"Resuming from {args.resume}")
        ckpt = torch.load(args.resume, map_location=cfg.device)
        model_cfg = NimbusConfig(**ckpt["model_config"])
        model = Nimbus(model_cfg)
        model.load_state_dict(ckpt["model"])
        iter_num = ckpt["iter_num"]
        best_val_loss = ckpt.get("best_val_loss", float("inf"))
    else:
        model = Nimbus(model_cfg)

    model.to(cfg.device)

    scaler = torch.cuda.amp.GradScaler(enabled=(cfg.dtype == "float16"))
    optimizer = model.configure_optimizers(
        weight_decay=cfg.weight_decay,
        learning_rate=cfg.learning_rate,
        betas=(cfg.beta1, cfg.beta2),
        device_type=device_type,
    )

    if args.resume and "optimizer" in ckpt:
        optimizer.load_state_dict(ckpt["optimizer"])

    if cfg.compile:
        print("Compiling model...")
        model = torch.compile(model)

    tokens_per_iter = cfg.grad_accum_steps * cfg.batch_size * cfg.block_size
    print(f"Tokens per iteration: {tokens_per_iter:,}")

    train_iter = iter(train_loader)
    t0 = time.time()
    model.train()

    while iter_num < cfg.max_iters:
        lr = get_lr(cfg, iter_num)
        for param_group in optimizer.param_groups:
            param_group["lr"] = lr

        if iter_num % cfg.eval_interval == 0:
            losses = estimate_loss(model, train_loader, val_loader, cfg, ctx)
            print(f"step {iter_num}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

            if losses["val"] < best_val_loss:
                best_val_loss = losses["val"]
                ckpt = {
                    "model": model.state_dict() if not cfg.compile else model._orig_mod.state_dict(),
                    "optimizer": optimizer.state_dict(),
                    "model_config": asdict(model_cfg),
                    "iter_num": iter_num,
                    "best_val_loss": best_val_loss,
                    "config": asdict(cfg),
                }
                torch.save(ckpt, os.path.join(cfg.out_dir, "ckpt.pt"))
                print(f"  Saved checkpoint (val loss {best_val_loss:.4f})")

        optimizer.zero_grad(set_to_none=True)
        for micro_step in range(cfg.grad_accum_steps):
            try:
                x, y = next(train_iter)
            except StopIteration:
                train_iter = iter(train_loader)
                x, y = next(train_iter)

            x, y = x.to(cfg.device), y.to(cfg.device)
            with ctx:
                _, loss = model(x, y)
                loss = loss / cfg.grad_accum_steps
            scaler.scale(loss).backward()

        if cfg.grad_clip > 0.0:
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), cfg.grad_clip)

        scaler.step(optimizer)
        scaler.update()

        t1 = time.time()
        dt = t1 - t0
        t0 = t1

        if iter_num % cfg.log_interval == 0:
            lossf = loss.item() * cfg.grad_accum_steps
            tokens_per_sec = tokens_per_iter / dt
            print(f"iter {iter_num:6d} | loss {lossf:.4f} | lr {lr:.2e} | {tokens_per_sec/1e3:.1f}k tok/s")

        iter_num += 1

    print("Training complete.")


if __name__ == "__main__":
    main()
